Disciplina: **Mineração de Dados**

Professor: **Wilson Castello Branco Neto**

Aula 2 - Exemplo 1: Medidas de Resumo para variáveis numéricas

Nome: Wilson Castello Branco Neto

**Dataset**: Gerado artificialmente com os seguintes campos:

1.   Idade
2.   Salário
3.   Função

Importação das bibliotecas necessárias para ler o arquivo do Google Drive, realizar as operações básicas sobre o dataset e gerar gráficos.

Montagem do drive para que o arquivo possa ser encontrado.

In [ ]:
import pandas as pd
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive

Leitura do arquivo CSV, armazenamento dos dados lidos no dataframe do Pandas e apresentação dos valores lidos.

In [ ]:
df = pd.read_csv('/content/gdrive/MyDrive/Ciência-de-Dados/Aula2_Exemplos.csv')

df

    Idade   Salário              Função
0      20   4133.73     Programador Jr.
1      48   9982.69     Programador Sr.
2      51   5947.86     Programador Jr.
3      51   7851.60  Cientista de Dados
4      23   5162.67     Programador Sr.
5      40  10326.69     Programador Sr.
6      66   9961.18  Cientista de Dados
7      24   1982.21     Programador Jr.
8      52   9447.06  Cientista de Dados
9      50   7586.70     Programador Jr.
10     84   6713.31     Programador Jr.
11     67  11492.63     Programador Sr.
12     81   9630.28  Cientista de Dados
13     54   9673.81     Programador Sr.
14     57   6409.72     Programador Jr.
15     43   3335.73     Programador Jr.
16     33   8245.96  Cientista de Dados
17     33   2528.83     Programador Jr.
18     66  12248.97  Cientista de Dados
19     29   9478.71     Programador Sr.

Apresentação dos dados sobre cada atributos (tipo e quantidade de valores não nulos).

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Idade    20 non-null     int64
 1   Salário  20 non-null     float64
 2   Função   20 non-null     object
dtypes: float64(1), int64(1), object(1)
memory usage: 612.0+ bytes

#**Parte 1 - Dados numéricos e categóricos unidimensionais**

Apresentação das estatíticas básicas dos atributos quantitativos.

In [ ]:
df.describe()

           Idade       Salário
count  20.000000     20.000000
mean   48.600000   7607.017000
std    18.391646   2988.089187
min    20.000000   1982.210000
25%    33.000000   5751.562500
50%    50.500000   8048.780000
75%    59.250000   9745.652500
max    84.000000  12248.970000

Cálculo das estatísticas básicas do atributo idade usando as funções do Pandas.

In [ ]:
quantidade = df['Idade'].count()
print('Quantidade de elementos: ', quantidade)

soma = df['Idade'].sum()
print('Soma dos elementos: ', soma)

media = df['Idade'].mean()
print('Media dos elementos: ', media)

mediana = df['Idade'].median()
print('Mediana dos elementos: ', mediana)

quartil1 = df['Idade'].quantile(q=0.25)
print('Quartil 1 dos elementos: ', quartil1)

quartil2 = df['Idade'].quantile(q=0.50)
print('Quartil 2 (mediana) dos elementos: ', quartil2)

quartil3 = df['Idade'].quantile(q=0.75)
print('Quartil 3 dos elementos: ', quartil3)

moda = df['Idade'].mode()
print('Moda dos elementos: ')
for x in moda:
  print(x)

minimo = df['Idade'].min()
print('Menor valor: ', minimo)

maximo = df['Idade'].max()
print('Maior valor: ', maximo)

var = df['Idade'].var()
print('Variância dos elementos: ', var)

dp = df['Idade'].std()
print('Desvio padrão dos elementos: ', dp)

cv = dp / media * 100
print('Coeficiente de variação dos elementos: ', cv)

assimetria = df['Idade'].skew()
print('Coeficiente de assimetria: ', assimetria)

curtose = df['Idade'].kurtosis()
print('Coeficiente de Curtose: ', curtose)

Quantidade de elementos:  20
Soma dos elementos:  972
Media dos elementos:  48.6
Mediana dos elementos:  50.5
Quartil 1 dos elementos:  33.0
Quartil 2 (mediana) dos elementos:  50.5
Quartil 3 dos elementos:  59.25
Moda dos elementos:
33
51
66
Menor valor:  20
Maior valor:  84
Variância dos elementos:  338.25263157894733
Desvio padrão dos elementos:  18.391645700669294
Coeficiente de variação dos elementos:  37.84289238820842
Coeficiente de assimetria:  0.23470164222576684
Coeficiente de Curtose:  -0.5631079894395468

Apresentação das estatíticas básicas dos atributos quantitativos e qualitativos.

In [ ]:
df.describe(include='all')

            Idade       Salário           Função
count   20.000000     20.000000               20
unique        NaN           NaN                3
top           NaN           NaN  Programador Jr.
freq          NaN           NaN                8
mean    48.600000   7607.017000              NaN
std     18.391646   2988.089187              NaN
min     20.000000   1982.210000              NaN
25%     33.000000   5751.562500              NaN
50%     50.500000   8048.780000              NaN
75%     59.250000   9745.652500              NaN
max     84.000000  12248.970000              NaN

Cálculo da quantidade de registros agrupados por função (distribuição de frequência)

In [ ]:
agrupadoFuncao = df.groupby(['Função']).size()

agrupadoFuncao

Função
Cientista de Dados    6
Programador Jr.       8
Programador Sr.       6
dtype: int64

#**Parte 2 - Dados multidimensionais**

Cálculo da covariância e da correlação entre as variáveis quantitativas do Dataframe.

Ao calcular o coeficiente de correlação deve-se indicar o tipo de cálculo a ser feito, por meio do parâmetro method, que pode receber os seguintes valores:

pearson (padrão);
kendall;
spearman.

In [ ]:
df.cov(numeric_only=True)

                Idade       Salário
Idade      338.252632  2.963334e+04
Salário  29633.341368  8.928677e+06

In [ ]:
df.corr(numeric_only=True)

            Idade   Salário
Idade    1.000000  0.539221
Salário  0.539221  1.000000

In [ ]:
df.corr(method='kendall',numeric_only=True)

            Idade   Salário
Idade    1.000000  0.366059
Salário  0.366059  1.000000

In [ ]:
df.corr(method='spearman',numeric_only=True)

            Idade   Salário
Idade    1.000000  0.520136
Salário  0.520136  1.000000

Dados multidimensionais categóricos e numéricos

Cálculo do salário médio de cada função.

Todas as funções estatísticas usadas para o tratamento de dados numéricos unidimensionais podem ser usadas para calcular os valores de cada um dos valores de um atributo numérico, após agrupar o dataset com base no atributo categórico.

In [ ]:
dfAgrupadoFuncao = df.groupby(['Função'])

salarioAgrupadoFuncao = dfAgrupadoFuncao['Salário'].mean()

salarioAgrupadoFuncao

Função
Cientista de Dados    9564.175000
Programador Jr.       4829.761250
Programador Sr.       9352.866667
Name: Salário, dtype: float64

In [ ]:
salarioAgrupadoFuncao = df.groupby(['Função'])['Salário'].mean()

salarioAgrupadoFuncao

Função
Cientista de Dados    9564.175000
Programador Jr.       4829.761250
Programador Sr.       9352.866667
Name: Salário, dtype: float64

O Agrupamento pode ser realizado por mais de um atributo, como nos exemplos a seguir.

Inserção no dataframe de um novo atributo, denominado Gênero, com os valores armazenados na lista.

In [ ]:
df['Gênero'] = ['M','F','M','F','M','F','M','F','M','F','M','F','M','F','M','F','M','F','M','F']

df

    Idade   Salário              Função Gênero
0      20   4133.73     Programador Jr.      M
1      48   9982.69     Programador Sr.      F
2      51   5947.86     Programador Jr.      M
3      51   7851.60  Cientista de Dados      F
4      23   5162.67     Programador Sr.      M
5      40  10326.69     Programador Sr.      F
6      66   9961.18  Cientista de Dados      M
7      24   1982.21     Programador Jr.      F
8      52   9447.06  Cientista de Dados      M
9      50   7586.70     Programador Jr.      F
10     84   6713.31     Programador Jr.      M
11     67  11492.63     Programador Sr.      F
12     81   9630.28  Cientista de Dados      M
13     54   9673.81     Programador Sr.      F
14     57   6409.72     Programador Jr.      M
15     43   3335.73     Programador Jr.      F
16     33   8245.96  Cientista de Dados      M
17     33   2528.83     Programador Jr.      F
18     66  12248.97  Cientista de Dados      M
19     29   9478.71     Programador Sr.      F

In [ ]:
dfAgrupadoFuncaoGenero = df.groupby(['Função','Gênero'])
salarioAgrupadoFuncaoGenero = dfAgrupadoFuncaoGenero['Salário'].mean()
salarioAgrupadoFuncaoGenero

Função              Gênero
Cientista de Dados  F          7851.6000
                    M          9906.6900
Programador Jr.     F          3858.3675
                    M          5801.1550
Programador Sr.     F         10190.9060
                    M          5162.6700
Name: Salário, dtype: float64

In [ ]:
dfAgrupadoFuncaoGenero = df.groupby(['Gênero','Função'])
salarioAgrupadoFuncaoGenero = dfAgrupadoFuncaoGenero['Salário'].mean()
salarioAgrupadoFuncaoGenero

Gênero  Função
F       Cientista de Dados     7851.6000
        Programador Jr.        3858.3675
        Programador Sr.       10190.9060
M       Cientista de Dados     9906.6900
        Programador Jr.        5801.1550
        Programador Sr.        5162.6700
Name: Salário, dtype: float64