Disciplina: **Mineração de Dados**

Professor: **Wilson Castello Branco Neto**

Aula 3 - Limpeza de Dados - Atividade 1

Nome: Wilson Castello Branco Neto

**Dataset**: Salary dataset based on country and race

Disponível em: https://www.kaggle.com/datasets/sudheerp2147234/salary-dataset-based-on-country-and-race

1.  Importe o dataset indicado e apresente seus dados, os tipos de cada uma de suas colunas e suas estatísticas básicas.
2.  Elimine a coluna Unnamed: 0.
3.  Verifique quantos valores ausentes (nulos) existem em cada atributo e elimine as linhas que contenham algum valor nulo.
4. Conte a quantidade de linhas duplicadas e elimine estas linhas.
5. Apresente e depois elimine os outliers do campo salário. Considere que um outlier será dado pelo valor da média +- 2 vezes o seu desvio padrão.
6. Verifique se há alguma dado inconsistente considerando os campos idade e anos de experiência. Considere que as pessoas só podem começar a trabalhar após os 16 anos de idade.
7.  Analise os dados e aplique mais alguma melhoria ao dataset resultante das transformações anteriores.

Importa e mostra dados

In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive

drive.mount('/content/gdrive/')

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).

In [ ]:
df = pd.read_csv("/content/gdrive/MyDrive/Aula3_At1_Salario.csv")

In [ ]:
df = pd.read_csv("/content/gdrive/MyDrive/Ciência-de-Dados/Aula3_At1_Salario.csv")

In [ ]:
df

,Unnamed: 0,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race
0,0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0,UK,White
1,1,28.0,Female,Master's,Data Analyst,3.0,65000.0,USA,Hispanic
2,2,45.0,Male,PhD,Senior Manager,15.0,150000.0,Canada,White
3,3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0,USA,Hispanic
4,4,52.0,Male,Master's,Director,20.0,200000.0,USA,Asian
...,...,...,...,...,...,...,...,...,...
6699,6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0,UK,Mixed
6700,6700,32.0,Male,High School,Sales Associate,3.0,50000.0,Australia,Australian
6701,6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0,China,Chinese
6702,6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0,China,Korean
6703,6703,26.0,Female,High School,Sales Executive,1.0,35000.0,Canada,Black

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           6704 non-null   int64
 1   Age                  6702 non-null   float64
 2   Gender               6702 non-null   object
 3   Education Level      6701 non-null   object
 4   Job Title            6702 non-null   object
 5   Years of Experience  6701 non-null   float64
 6   Salary               6699 non-null   float64
 7   Country              6704 non-null   object
 8   Race                 6704 non-null   object
dtypes: float64(3), int64(1), object(5)
memory usage: 471.5+ KB

In [ ]:
df.describe(include="all")

,Unnamed: 0,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race
count,6704.000000,6702.000000,6702,6701,6702,6701.000000,6699.000000,6704,6704
unique,NaN,NaN,3,7,193,NaN,NaN,5,10
top,NaN,NaN,Male,Bachelor's Degree,Software Engineer,NaN,NaN,USA,White
freq,NaN,NaN,3674,2267,518,NaN,NaN,1360,1968
mean,3351.500000,33.620859,NaN,NaN,NaN,8.094687,115326.964771,NaN,NaN
std,1935.422435,7.614633,NaN,NaN,NaN,6.059003,52786.183911,NaN,NaN
min,0.000000,21.000000,NaN,NaN,NaN,0.000000,350.000000,NaN,NaN
25%,1675.750000,28.000000,NaN,NaN,NaN,3.000000,70000.000000,NaN,NaN
50%,3351.500000,32.000000,NaN,NaN,NaN,7.000000,115000.000000,NaN,NaN
75%,5027.250000,38.000000,NaN,NaN,NaN,12.000000,160000.000000,NaN,NaN
max,6703.000000,62.000000,NaN,NaN,NaN,34.000000,250000.000000,NaN,NaN

2.Remove Coluna Unnamed

In [ ]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [ ]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0,UK,White
1,28.0,Female,Master's,Data Analyst,3.0,65000.0,USA,Hispanic
2,45.0,Male,PhD,Senior Manager,15.0,150000.0,Canada,White
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0,USA,Hispanic
4,52.0,Male,Master's,Director,20.0,200000.0,USA,Asian
...,...,...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0,UK,Mixed
6700,32.0,Male,High School,Sales Associate,3.0,50000.0,Australia,Australian
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0,China,Chinese
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0,China,Korean
6703,26.0,Female,High School,Sales Executive,1.0,35000.0,Canada,Black


3. Verifique quantos valores ausentes (nulos) existem em cada atributo e elimine as linhas que contenham algum valor nulo.

In [ ]:
nulos = pd.isnull(df).sum()
print(nulos)

Age                    2
Gender                 2
Education Level        3
Job Title              2
Years of Experience    3
Salary                 5
Country                0
Race                   0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0,UK,White
1,28.0,Female,Master's,Data Analyst,3.0,65000.0,USA,Hispanic
2,45.0,Male,PhD,Senior Manager,15.0,150000.0,Canada,White
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0,USA,Hispanic
4,52.0,Male,Master's,Director,20.0,200000.0,USA,Asian
...,...,...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0,UK,Mixed
6700,32.0,Male,High School,Sales Associate,3.0,50000.0,Australia,Australian
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0,China,Chinese
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0,China,Korean
6703,26.0,Female,High School,Sales Executive,1.0,35000.0,Canada,Black

4. Remove Duplicados

In [ ]:
duplicates = df.duplicated().sum()
print(duplicates)

1535

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0,UK,White
1,28.0,Female,Master's,Data Analyst,3.0,65000.0,USA,Hispanic
2,45.0,Male,PhD,Senior Manager,15.0,150000.0,Canada,White
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0,USA,Hispanic
4,52.0,Male,Master's,Director,20.0,200000.0,USA,Asian
...,...,...,...,...,...,...,...,...
6698,37.0,Male,Bachelor's Degree,Junior Sales Representative,6.0,75000.0,Canada,Asian
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0,UK,Mixed
6700,32.0,Male,High School,Sales Associate,3.0,50000.0,Australia,Australian
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0,China,Chinese
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0,China,Korean

5. Apresente e depois elimine os outliers do campo salário. Considere que um outlier será dado pelo valor da média +- 2 vezes o seu desvio padrão.

In [ ]:

df.describe(include='all')

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race
count,5163.000000,5163,5163,5163,5163.000000,5163.000000,5163,5163
unique,NaN,3,7,191,NaN,NaN,5,10
top,NaN,Male,Bachelor's Degree,Software Engineer,NaN,NaN,USA,White
freq,NaN,2808,1690,331,NaN,NaN,1079,1519
mean,34.009878,NaN,NaN,NaN,8.352315,114267.969010,NaN,NaN
std,7.782401,NaN,NaN,NaN,6.264884,52447.051011,NaN,NaN
min,21.000000,NaN,NaN,NaN,0.000000,350.000000,NaN,NaN
25%,28.000000,NaN,NaN,NaN,3.000000,69516.000000,NaN,NaN
50%,32.000000,NaN,NaN,NaN,7.000000,113334.000000,NaN,NaN
75%,39.000000,NaN,NaN,NaN,12.000000,160000.000000,NaN,NaN
max,62.000000,NaN,NaN,NaN,34.000000,250000.000000,NaN,NaN

In [ ]:
limite_inferior = df['Salary'].mean() - 2 * df['Salary'].std()
limite_superior = df['Salary'].mean() + 2 * df['Salary'].std()

print('limite inferior:', limite_inferior)
print('limite superior:', limite_superior)
print('Dados fora dos limites:')
df[(df['Salary'] < limite_inferior) | (df['Salary'] > limite_superior)]

limite inferior: 9373.86698758103
limite superior: 219162.07103294967
Dados fora dos limites:

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race
30,50.0,Male,Bachelor's,CEO,25.0,250000.0,Canada,Asian
83,52.0,Male,PhD,Chief Technology Officer,24.0,250000.0,Canada,Black
105,44.0,Male,PhD,Chief Data Officer,16.0,220000.0,USA,African American
259,29.0,Male,Bachelor's,Junior Business Operations Analyst,1.5,350.0,USA,Hispanic
1890,25.0,Female,Bachelor's Degree,Front end Developer,1.0,550.0,UK,Mixed
2260,46.0,Female,PhD,Director of Data Science,20.0,220000.0,USA,White
2654,23.0,Male,PhD,Software Engineer Manager,1.0,579.0,UK,Mixed
2664,46.0,Male,PhD,Director of Data Science,20.0,220000.0,Canada,Asian
4027,49.0,Male,PhD,Data Scientist,22.0,220000.0,UK,White
4042,49.0,Male,PhD,Data Scientist,22.0,220000.0,UK,Mixed
4057,49.0,Male,PhD,Data Scientist,22.0,220000.0,China,White
4072,49.0,Male,PhD,Data Scientist,22.0,220000.0,Australia,Asian
4087,49.0,Male,PhD,Data Scientist,22.0,220000.0,Canada,White
4102,49.0,Male,PhD,Data Scientist,22.0,220000.0,USA,Hispanic
4152,50.0,Male,PhD,Data Scientist,23.0,225000.0,UK,Asian
4167,50.0,Male,PhD,Data Scientist,23.0,225000.0,USA,Hispanic
4182,50.0,Male,PhD,Data Scientist,23.0,225000.0,Australia,Australian
4212,50.0,Male,PhD,Data Scientist,23.0,225000.0,Australia,White
4227,50.0,Male,PhD,Data Scientist,23.0,225000.0,UK,White
4257,50.0,Male,PhD,Data Scientist,23.0,225000.0,UK,Welsh
4276,51.0,Male,PhD,Data Scientist,24.0,240000.0,Canada,Black
4291,51.0,Male,PhD,Data Scientist,24.0,240000.0,UK,Welsh
4306,51.0,Male,PhD,Data Scientist,24.0,240000.0,China,Korean
4321,51.0,Male,PhD,Data Scientist,24.0,240000.0,China,Chinese
4336,51.0,Male,PhD,Data Scientist,24.0,240000.0,USA,White
4366,51.0,Male,PhD,Data Scientist,24.0,240000.0,Canada,White
4381,51.0,Male,PhD,Data Scientist,24.0,240000.0,Canada,Asian
4397,49.0,Male,Master's Degree,Marketing Manager,23.0,228000.0,Canada,White
4633,31.0,Female,Bachelor's Degree,Junior HR Coordinator,4.0,500.0,USA,Asian
5001,45.0,Male,Bachelor's Degree,Financial Manager,21.0,250000.0,Canada,Black

In [ ]:
df = df[(df['Salary']<=limite_superior) & (df['Salary']>=limite_inferior)]

df.describe(include='all')

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race
count,5133.000000,5133,5133,5133,5133.000000,5133.000000,5133,5133
unique,NaN,3,7,188,NaN,NaN,5,10
top,NaN,Male,Bachelor's Degree,Software Engineer,NaN,NaN,USA,White
freq,NaN,2781,1687,331,NaN,NaN,1072,1510
mean,33.937658,NaN,NaN,NaN,8.285311,113768.857393,NaN,NaN
std,7.723824,NaN,NaN,NaN,6.196634,51842.465511,NaN,NaN
min,21.000000,NaN,NaN,NaN,0.000000,25000.000000,NaN,NaN
25%,28.000000,NaN,NaN,NaN,3.000000,68611.000000,NaN,NaN
50%,32.000000,NaN,NaN,NaN,7.000000,111535.000000,NaN,NaN
75%,39.000000,NaN,NaN,NaN,12.000000,160000.000000,NaN,NaN
max,62.000000,NaN,NaN,NaN,34.000000,219000.000000,NaN,NaN

In [ ]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0,UK,White
1,28.0,Female,Master's,Data Analyst,3.0,65000.0,USA,Hispanic
2,45.0,Male,PhD,Senior Manager,15.0,150000.0,Canada,White
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0,USA,Hispanic
4,52.0,Male,Master's,Director,20.0,200000.0,USA,Asian
...,...,...,...,...,...,...,...,...
6698,37.0,Male,Bachelor's Degree,Junior Sales Representative,6.0,75000.0,Canada,Asian
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0,UK,Mixed
6700,32.0,Male,High School,Sales Associate,3.0,50000.0,Australia,Australian
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0,China,Chinese
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0,China,Korean

6.Verifique se há alguma dado inconsistente considerando os campos idade e anos de experiência. Considere que as pessoas só podem começar a trabalhar após os 16 anos de idade.

In [ ]:
df['Inconsistent'] = ((df['Age'] - df['Years of Experience']) < 16)
df[df['Inconsistent'] == True]

/tmp/ipython-input-4101004061.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Inconsistent'] = ((df['Age'] - df['Years of Experience']) < 16)

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race,Inconsistent
2376,25.0,Male,PhD,Software Engineer Manager,12.0,169159.0,China,Chinese,True
2456,25.0,Male,PhD,Software Engineer Manager,12.0,169159.0,China,White,True

In [ ]:
df.drop(labels=df[df['Inconsistent'] == True].index, inplace=True)

/tmp/ipython-input-3595505543.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(labels=df[df['Inconsistent'] == True].index, inplace=True)

In [ ]:
df.drop(columns=['Inconsistent'], inplace=True)

/tmp/ipython-input-3849195458.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['Inconsistent'], inplace=True)

In [ ]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0,UK,White
1,28.0,Female,Master's,Data Analyst,3.0,65000.0,USA,Hispanic
2,45.0,Male,PhD,Senior Manager,15.0,150000.0,Canada,White
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0,USA,Hispanic
4,52.0,Male,Master's,Director,20.0,200000.0,USA,Asian
...,...,...,...,...,...,...,...,...
6698,37.0,Male,Bachelor's Degree,Junior Sales Representative,6.0,75000.0,Canada,Asian
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0,UK,Mixed
6700,32.0,Male,High School,Sales Associate,3.0,50000.0,Australia,Australian
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0,China,Chinese
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0,China,Korean